---
title: "Test nabla_LB function"
output: html_notebook
---


set up

```{r}
library(Rcpp)
library(simmr)
```


Data 2 iso
```{r}
mix = matrix(c(-10.13, -10.72, -11.39, -11.18, -10.81, -10.7, -10.54, 
               -10.48, -9.93, -9.37, 11.59, 11.01, 10.59, 10.97, 11.52, 11.89, 
               11.73, 10.89, 11.05, 12.3), ncol = 2, nrow = 10)
colnames(mix) = c('d13C','d15N')
s_names = c("Zostera", "Grass", "U.lactuca", "Enteromorpha")
s_means = matrix(c(-14, -15.1, -11.03, -14.44, 3.06, 7.05, 13.72, 5.96), ncol = 2, nrow = 4)
s_sds = matrix(c(0.48, 0.38, 0.48, 0.43, 0.46, 0.39, 0.42, 0.48), ncol = 2, nrow = 4)
c_means = matrix(c(2.63, 1.59, 3.41, 3.04, 3.28, 2.34, 2.14, 2.36), ncol = 2, nrow = 4)
c_sds = matrix(c(0.41, 0.44, 0.34, 0.46, 0.46, 0.48, 0.46, 0.66), ncol = 2, nrow = 4)
conc = matrix(c(0.02, 0.1, 0.12, 0.04, 0.02, 0.1, 0.09, 0.05), ncol = 2, nrow = 4)
```



Data 1 iso

```{r}
mix = matrix(c(-10.13, -10.72, -11.39, -11.18, -10.81, -10.7, -10.54, 
               -10.48, -9.93, -9.37), ncol = 1, nrow = 10)
colnames(mix) = c('d13C')
s_names = c("Zostera", "Grass", "U.lactuca", "Enteromorpha")
s_means = matrix(c(-14, -15.1, -11.03, -14.44), ncol = 1, nrow = 4)
s_sds = matrix(c(0.48, 0.38, 0.48, 0.43), ncol = 1, nrow = 4)
c_means = matrix(c(2.63, 1.59, 3.41, 3.04), ncol = 1, nrow = 4)
c_sds = matrix(c(0.41, 0.44, 0.34, 0.46), ncol = 1, nrow = 4)
conc = matrix(c(0.02, 0.1, 0.12, 0.04), ncol = 1, nrow = 4)
```



simmr in
```{r}
simmr_in = simmr_load(mixtures = mix,
                     source_names = s_names,
                     source_means = s_means,
                     source_sds = s_sds,
                     correction_means = c_means,
                     correction_sds = c_sds,
                     concentration_means = conc)
```


Need to create lambda and theta for now
```{r}
K = simmr_in$n_sources
n_tracers = simmr_in$n_tracers
lambda = c(rep(2, K+K*(K+1)/2 +n_tracers*2))

theta<-matrix(c(1,2,6,3,2,8,5,4,6,2,9,6, 4,3,2,5,4,3), ncol = 6)
```




```{r}
prior_control = list(
                       means = rep(
                         1,
                         simmr_in$n_sources),
                       sd = rep(
                         1,
                         simmr_in$n_sources),
                       c_0 = rep(
                         1,
                         simmr_in$n_tracers),
                       d_0 = rep(
                         1,
                         simmr_in$n_tracers))

output <- vector("list", length = simmr_in$n_groups)
  names(output) <- levels(simmr_in$group)
  K<-simmr_in$n_sources
  n_tracers <- simmr_in$n_tracers
  lambdares<-matrix(rep(NA, ((( K + (K * (K + 1)) / 2)) + n_tracers * 2) * simmr_in$n_groups),
                    nrow =((( K + (K * (K + 1)) / 2)) + n_tracers * 2),
                    ncol = simmr_in$n_groups)
  
  curr_mix <- simmr_in$mixtures
  
      n_tracers <- simmr_in$n_tracers
    n_sources <- simmr_in$n_sources
    s_names <- simmr_in$source_names
    K<-simmr_in$n_sources
    S <- 100
    source_means = simmr_in$source_means
    source_sds = simmr_in$source_sds
    correction_means = simmr_in$correction_means
    correction_sds = simmr_in$correction_sds
    concentration_means = simmr_in$concentration_means
    y = curr_mix
    
    
     log_q = function(lambda, theta) {
      mean <- lambda[1:K]
      # K*(K-1) precision terms
      chol_prec <- matrix(0, nrow = K, ncol = K)
      chol_prec[upper.tri(chol_prec, diag = TRUE)] <- lambda[(K + 1):(K + (K * (K + 1)) / 2)]
      # chol_prec[1,3] <- 0
      
      # This is a placeholder for more advanced code using chol_prec directly
      # prec <- crossprod(chol_prec)
      p1 <- matrix(theta[1:K] - mean, nrow = 1) %*% t(chol_prec)
      # log_det <- unlist(determinant(prec, logarithm = TRUE))["modulus"]
      return(-0.5 * K * log(2 * pi) - 0.5 * sum(log(diag(chol_prec))) - 0.5 * p1%*%t(p1)
             + sum(dgamma(theta[(K + 1):(K + n_tracers)],
                          shape = lambda[((K + (K * (K + 1)) / 2) + 1):(((K + (K * (K + 1)) / 2)) + n_tracers)],
                          rate = lambda[(((K + (K * (K + 1)) / 2)) + n_tracers + 1):(((K + (K * (K + 1)) / 2)) + n_tracers * 2)],
                          log = TRUE
             )))
     }
     
      h = function(theta) {
      p <- exp(theta[1:K]) / (sum((exp(theta[1:K])))) #slightly hacky way of doing 1 or
      return(ifelse((simmr_in$n_tracers == 2), 
                    (sum(dnorm(y[, 1],
                        mean = sum(p * concentration_means[,1] * (source_means[, 1]+correction_means[,1]))/sum(p*concentration_means[,1]),
                        sd = sqrt(sum(p^2 * concentration_means[,1]^2 * (source_sds[, 1]^2+correction_sds[,1]^2))/sum(p^2*concentration_means[,1]^2) + 1 / theta[K + 1]),
                        log = TRUE)) +
                    sum(dnorm(y[, 2],
                      mean = sum(p * concentration_means[,2] * (source_means[, 2]+correction_means[,2]))/sum(p*concentration_means[,2]),
                      sd = sqrt(sum(p^2 * concentration_means[,2]^2 * (source_sds[, 2]^2+correction_sds[,2]^2))/sum(p^2*concentration_means[,2]^2) + 1 / theta[K + 2]),
                      log = TRUE))), 
                    (sum(dnorm(y,
                              mean = sum(p * concentration_means * (source_means+correction_means))/sum(p*concentration_means),
                              sd = sqrt(sum(p^2 * concentration_means^2 * (source_sds[, 1]^2+correction_sds^2))/sum(p^2*concentration_means^2) + 1 / theta[K + 1]),
                              log = TRUE
        )))) +
        sum(dnorm(theta[1:K], prior_control$means, prior_control$sd, log = TRUE)) +
        sum(dgamma(theta[(K + 1):(K + n_tracers)], shape = prior_control$c_0, rate = prior_control$d_0, log = TRUE)))
      }
      
    h_lambda <- function(lambda, theta, y) {
      return(h(theta) - log_q(lambda, theta))
    }
    
    delta_lqlt <- function(lambda, theta, eps = 0.001) {
      k <- length(lambda)
      ans <- rep(NA, k)
      for (i in 1:k) {
        d <- rep(0, k)
        d[i] <- eps
        ans[i] <- (log_q(lambda + d, theta) - log_q(lambda - d, theta)) / (2 * max(d))
      }
      return(ans)
       }
       
   # Nable LB is the mean of delta_lqlt element-wise multiplied by h_lambda
    nabla_LB <- function(lambda, theta, c = rep(0, length(lambda))) {
      big_delta_lqlt <- t(apply(theta, 1, delta_lqlt, lambda = lambda))
      big_h_lambda <- t(apply(theta, 1, h_lambda, lambda = lambda, y = y))
      big_h_lambda_rep <- matrix(rep(big_h_lambda, length(lambda)),
                                 nrow = nrow(theta),
                                 ncol = length(lambda)
      )
      big_c <- matrix(rep(c, nrow(theta)),
                      ncol = length(c),
                      nrow = nrow(theta),
                      byrow = TRUE
      )
      return(colMeans(big_delta_lqlt * (big_h_lambda_rep - c)))
    }
    
    c = rep(0, length(lambda))
    nabla_LB(lambda, theta, c)
```




```{r}
c = rep(0, length(lambda))
nabla_LB_cpp(lambda, theta, simmr_in$n_sources,  simmr_in$n_tracers,
                  simmr_in$concentration_means,simmr_in$source_means,
                  simmr_in$correction_means,
                  simmr_in$correction_sds, simmr_in$source_sds, simmr_in$mix,
                  c)


# microbenchmark(nabla_LB(lambda, theta, c),nabla_LB_cpp(lambda, theta, simmr_in$n_sources,  simmr_in$n_tracers,
#                   simmr_in$concentration_means,simmr_in$source_means,
#                   simmr_in$correction_means,
#                   simmr_in$correction_sds, simmr_in$source_sds, simmr_in$mix,
#                   c))
```





