---
title: "Test sim theta"
output: html_notebook
---


set up

```{r}
library(Rcpp)
library(simmr)
```


Data 2 iso
```{r}
mix = matrix(c(-10.13, -10.72, -11.39, -11.18, -10.81, -10.7, -10.54, 
               -10.48, -9.93, -9.37, 11.59, 11.01, 10.59, 10.97, 11.52, 11.89, 
               11.73, 10.89, 11.05, 12.3), ncol = 2, nrow = 10)
colnames(mix) = c('d13C','d15N')
s_names = c("Zostera", "Grass", "U.lactuca", "Enteromorpha")
s_means = matrix(c(-14, -15.1, -11.03, -14.44, 3.06, 7.05, 13.72, 5.96), ncol = 2, nrow = 4)
s_sds = matrix(c(0.48, 0.38, 0.48, 0.43, 0.46, 0.39, 0.42, 0.48), ncol = 2, nrow = 4)
c_means = matrix(c(2.63, 1.59, 3.41, 3.04, 3.28, 2.34, 2.14, 2.36), ncol = 2, nrow = 4)
c_sds = matrix(c(0.41, 0.44, 0.34, 0.46, 0.46, 0.48, 0.46, 0.66), ncol = 2, nrow = 4)
conc = matrix(c(0.02, 0.1, 0.12, 0.04, 0.02, 0.1, 0.09, 0.05), ncol = 2, nrow = 4)
```



Data 1 iso

```{r}
mix = matrix(c(-10.13, -10.72, -11.39, -11.18, -10.81, -10.7, -10.54, 
               -10.48, -9.93, -9.37), ncol = 1, nrow = 10)
colnames(mix) = c('d13C')
s_names = c("Zostera", "Grass", "U.lactuca", "Enteromorpha")
s_means = matrix(c(-14, -15.1, -11.03, -14.44), ncol = 1, nrow = 4)
s_sds = matrix(c(0.48, 0.38, 0.48, 0.43), ncol = 1, nrow = 4)
c_means = matrix(c(2.63, 1.59, 3.41, 3.04), ncol = 1, nrow = 4)
c_sds = matrix(c(0.41, 0.44, 0.34, 0.46), ncol = 1, nrow = 4)
conc = matrix(c(0.02, 0.1, 0.12, 0.04), ncol = 1, nrow = 4)
```



simmr in
```{r}
simmr_in = simmr_load(mixtures = mix,
                     source_names = s_names,
                     source_means = s_means,
                     source_sds = s_sds,
                     correction_means = c_means,
                     correction_sds = c_sds,
                     concentration_means = conc)
```


Need to create lambda and theta for now
```{r}
K = simmr_in$n_sources
n_tracers = simmr_in$n_tracers
lambda = c(rep(1, K+K*(K+1)/2 +n_tracers*2))

theta<-matrix(c(1,2,6,3,2,8,5,4,6,2,9,6), ncol = 6)
```




```{r}
prior_control = list(
                       means = rep(
                         1,
                         simmr_in$n_sources),
                       sd = rep(
                         1,
                         simmr_in$n_sources),
                       c_0 = rep(
                         1,
                         simmr_in$n_tracers),
                       d_0 = rep(
                         1,
                         simmr_in$n_tracers))

output <- vector("list", length = simmr_in$n_groups)
  names(output) <- levels(simmr_in$group)
  K<-simmr_in$n_sources
  n_tracers <- simmr_in$n_tracers
  lambdares<-matrix(rep(NA, ((( K + (K * (K + 1)) / 2)) + n_tracers * 2) * simmr_in$n_groups),
                    nrow =((( K + (K * (K + 1)) / 2)) + n_tracers * 2),
                    ncol = simmr_in$n_groups)
  
  curr_mix <- simmr_in$mixtures
  
      n_tracers <- simmr_in$n_tracers
    n_sources <- simmr_in$n_sources
    s_names <- simmr_in$source_names
    K<-simmr_in$n_sources
    S <- 100
    source_means = simmr_in$source_means
    source_sds = simmr_in$source_sds
    correction_means = simmr_in$correction_means
    correction_sds = simmr_in$correction_sds
    concentration_means = simmr_in$concentration_means
    y = curr_mix
    
    rMVNormC <- function(n, mu, U){
    p <- length(mu)
    Z <- matrix(rnorm(p*n), p, n)
    # U <- chol(Omega) # By default R's chol fxn returns upper cholesky factor
    X <- backsolve(U, Z) # more efficient and stable than actually inverting
    X <- sweep(X, 1, mu, FUN=`+`)
    return(X)
  }
    
    
   sim_theta = function(S, lambda) {
      
      # For K parameters you will have
      # lambda is of length K+K*(K+1)/2 +n_tracers*2
      # mean <- lambda[1:K]
      # chol_prec is made up of lambda[(K + 1):(K+(K*(K+1))/2)]
      # Tau is made up of lambda[((K+(K*(K+1))/2)+1):((K+(K*(K+1))/2)+n_tracers*2)]
      # (f) ~ MVN(lambda[1:K], solve(crossprod(chol_prec)))
      
      
      mean <- lambda[1:K]
      # K*(K-1) precision terms
      chol_prec <- matrix(0, nrow = K, ncol = K)
      chol_prec[upper.tri(chol_prec, diag = TRUE)] <- lambda[(K + 1):(K + (K * (K + 1)) / 2)]
      
      # This is a placeholder for more advanced code using chol_prec directly
      theta <- cbind(
        t(rMVNormC(S, mu = mean, U = chol_prec)),
        matrix(rgamma(S * n_tracers,
                      shape = lambda[((K + (K * (K + 1)) / 2) + 1):(((K + (K * (K + 1)) / 2)) + n_tracers)],
                      rate = lambda[(((K + (K * (K + 1)) / 2)) + n_tracers + 1):(((K + (K * (K + 1)) / 2)) + n_tracers * 2)]
        ),
        nrow = S,
        ncol = n_tracers,
        byrow = TRUE
        )
      )
      
      return(theta)
   }
   
f<-sim_theta(S, lambda)
   
```

```{r}
S = 100
K = n_sources
 mean <- lambda[1:K]
chol_prec <- matrix(0, nrow = K, ncol = K)
chol_prec[upper.tri(chol_prec, diag = TRUE)] <- lambda[(K + 1):(K + (K * (K + 1)) / 2)]
x<-t(rMVNormC(S, mu = mean, U = chol_prec))

e<-sim_thetacpp(S, lambda, n_sources, n_tracers, x)
```
   
   
   